
CREATE TABLE IF NOT EXISTS TB_STATUS_GROUP(

    STATUS_GROUP_ID INT  ,
    STATUS_GROUP_NAME VARCHAR(20),
    CONSTRAINT STATUS_GROUP_PK PRIMARY KEY (STATUS_GROUP_ID)

);

CREATE TABLE IF NOT EXISTS TB_STATUS_CODE(

    STATUS_CODE_ID VARCHAR(4),
    STATUS_CODE_GROUP_ID INT NOT NULL,
    STATUS_CODE_NAME VARCHAR(20) NOT NULL,
    CONSTRAINT STATUS_CODE_ID_FK
        FOREIGN KEY (STATUS_CODE_GROUP_ID)
        REFERENCES TB_STATUS_GROUP(STATUS_GROUP_ID),
    CONSTRAINT TB_STATUS_CODE_PK
        PRIMARY KEY (STATUS_CODE_ID)

);

CREATE TABLE IF NOT EXISTS TB_MEMBER(

    MEMBER_UUID VARCHAR(36),
    MEMBER_ROLE VARCHAR(4) NOT NULL,
    MEMBER_NAME VARCHAR(20) NOT NULL,
    MEMBER_RRN VARCHAR(15) NOT NULL UNIQUE,
    MEMBER_PHONE VARCHAR(15) NOT NULL UNIQUE,
    MEMBER_CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    MEMBER_UPDATE_DATE DATETIME,
    MEMBER_DELETE_DATE DATETIME,
    CONSTRAINT TB_MEMBER_PK
        PRIMARY KEY (MEMBER_UUID),
    CONSTRAINT MEMBER_ROLE_CHK
        CHECK ( MEMBER_ROLE LIKE 'R%' ),
    CONSTRAINT MEMBER_ROLE_FK
        FOREIGN KEY (MEMBER_ROLE)
        REFERENCES TB_STATUS_CODE(STATUS_CODE_ID)

);