CREATE TABLE TB_RECEPTION (
    UUID VARCHAR(36) default (UUID()) PRIMARY KEY,
    PATIENT_UUID VARCHAR(36),
    DOCTOR_UUID VARCHAR(36),
    STATUS VARCHAR(4) DEFAULT 'RE01',
    NAME VARCHAR(20),
    RRN VARCHAR(15),
    SYMPTOM VARCHAR(300),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    DELETE_DATE DATETIME,
    CONSTRAINT FK_TB_RECEPTION_STATUS_CODE FOREIGN KEY (STATUS)
    	REFERENCES tb_status_code(id),
    CONSTRAINT FK_TB_RECEPTION_MEMBER_UUID FOREIGN KEY (PATIENT_UUID)
    	REFERENCES TB_MEMBER(uuid),
    CONSTRAINT FK_TB_RECEPTION_DOCTOR_UUID FOREIGN KEY (DOCTOR_UUID)
    	REFERENCES TB_MEMBER(uuid)
);

