create table 
    TB_RESERVATION
    (
        ID VARCHAR(36) default (UUID()) PRIMARY key,
        PATIENT_UUID VARCHAR(36),
        DOCTOR_UUID VARCHAR(36),
        STATUS VARCHAR(4),
        RESERVATION_DATE DATETIME,
        SYMPTOM VARCHAR(300),
        CONSTRAINT FK_TB_RESERVATION_STATUS_CODE FOREIGN KEY (STATUS)
        REFERENCES tb_status_code(id),
    	CONSTRAINT FK_TB_RESERVATION_MEMBER_UUID FOREIGN KEY (PATIENT_UUID)
        REFERENCES TB_MEMBER(uuid),
    	CONSTRAINT FK_TB_RESERVATION_DOCTOR_UUID FOREIGN KEY (DOCTOR_UUID)
        REFERENCES TB_MEMBER(uuid)
	);