CREATE TABLE `TB_DIAGNOSIS` (
  `id` int(11) NOT NULL,
  `treatment_id` int(11) NOT NULL,
  KEY `TB_DIAGNOSIS_TB_TREATMENT_FK` (`treatment_id`),
  KEY `TB_DIAGNOSIS_TB_DISEASE_FK` (`id`),
  CONSTRAINT `TB_DIAGNOSIS_TB_DISEASE_FK` FOREIGN KEY (`id`) REFERENCES `TB_DISEASE` (`id`),
  CONSTRAINT `TB_DIAGNOSIS_TB_TREATMENT_FK` FOREIGN KEY (`treatment_id`) REFERENCES `TB_TREATMENT` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;