CREATE TABLE `TB_PRESCRIPTION` (
  `code` varchar(10) NOT NULL,
  `treatment_id` int(11) NOT NULL,
  `volume` int(11) NOT NULL,
  KEY `TB_PRESCRIPTION_TB_MEDICINE_FK` (`code`),
  KEY `TB_PRESCRIPTION_TB_TREATMENT_FK` (`treatment_id`),
  CONSTRAINT `TB_PRESCRIPTION_TB_MEDICINE_FK` FOREIGN KEY (`code`) REFERENCES `TB_MEDICINE` (`code`),
  CONSTRAINT `TB_PRESCRIPTION_TB_TREATMENT_FK` FOREIGN KEY (`treatment_id`) REFERENCES `TB_TREATMENT` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;